on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'test github'
        run: pwd

      - name: Print a message
        run: echo "Build job triggered successfully!"