on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'printing folder content'
        run: pwd

      #- name: 'test print'
      #  run: echo mostafa